version: "2"

services:
  # app server
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: app
    image: juju
    volumes:
      - .:/app/juju
    command: ./docker/app/run_app.sh
    ports:
      - "8080:8080"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    environment:
      redis_host: "redis"

  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'


  # Celery beat
  beat:
    image: juju
    volumes:
      - .:/app/juju
    command: ./docker/beat/run_beat.sh
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
    environment:
      redis_host: "redis"
      mongo_host: "mongo"

  # Celery worker
  worker:
    image: juju
    volumes:
      - .:/app/juju
    command: ./docker/worker/run_worker.sh
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    environment:
      redis_host: "redis"

  # Redis
  redis:
    image: redis:4.0.9
    hostname: redis

volumes:
  postgres:
  redis:
