version: "2"

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:10.3-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  web:
    build: "."
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "cli.app:main"
    depends_on:
      - "postgres"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"


volumes:
  postgres: {}
