POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "again100",
    "password": "123"
}

### Authorization by token, part 2. Use token to authorize.
GET http://localhost:5000/user/protected
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjcyNTg4MzYsImV4cCI6MTUyNzM0NTIzNiwicmZfZXhwIjoxNTI5ODUwODM2LCJqdGkiOiI3MzYzMzBmYy05YmY5LTRiYzctOWFkMC0yODNiOGE5NjE3ZTYiLCJpZCI6MywicmxzIjoiY2FuX25vdGhpbmcifQ.QfTOc0xJrkQnBjS7gN5wxucsvr8NeGQzlYQcKJOF9oQ

###
GET http://localhost:5000/user/protected_admin_required
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjcxOTUzNzAsImV4cCI6MTUyNzI4MTc3MCwicmZfZXhwIjoxNTI5Nzg3MzcwLCJqdGkiOiJlY2JkNTU1Yy0zNTY5LTRmZmQtOTU1Zi1hZjBmZWNkMDQ2MzYiLCJpZCI6MywicmxzIjoiY2FuX25vdGhpbmcifQ.Yky5oaL7lS3lrRtAB5f_dMLW2crMpWo9rmlpfWUx17Y

###
GET http://localhost:5000/user/protected_operator_accepted
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjcxOTUzNzAsImV4cCI6MTUyNzI4MTc3MCwicmZfZXhwIjoxNTI5Nzg3MzcwLCJqdGkiOiJlY2JkNTU1Yy0zNTY5LTRmZmQtOTU1Zi1hZjBmZWNkMDQ2MzYiLCJpZCI6MywicmxzIjoiY2FuX25vdGhpbmcifQ.Yky5oaL7lS3lrRtAB5f_dMLW2crMpWo9rmlpfWUx17Y

###
GET http://localhost:5000/user/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjcyNTg4MzYsImV4cCI6MTUyNzM0NTIzNiwicmZfZXhwIjoxNTI5ODUwODM2LCJqdGkiOiI3MzYzMzBmYy05YmY5LTRiYzctOWFkMC0yODNiOGE5NjE3ZTYiLCJpZCI6MywicmxzIjoiY2FuX25vdGhpbmcifQ.QfTOc0xJrkQnBjS7gN5wxucsvr8NeGQzlYQcKJOF9oQ


###
POST http://localhost:5000/user/disable_user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjcyNTg4MzYsImV4cCI6MTUyNzM0NTIzNiwicmZfZXhwIjoxNTI5ODUwODM2LCJqdGkiOiI3MzYzMzBmYy05YmY5LTRiYzctOWFkMC0yODNiOGE5NjE3ZTYiLCJpZCI6MywicmxzIjoiY2FuX25vdGhpbmcifQ.QfTOc0xJrkQnBjS7gN5wxucsvr8NeGQzlYQcKJOF9oQ

{
    "username": "again100"

}

###
GET http://localhost:5000/user
Content-Type: application/json

###

GET http://localhost:5000/user/usernames
Content-Type: application/json




### Send POST request with json body
POST http://localhost:5000/user
Content-Type: application/json


{
  "username": "again10",
  "name": "Layth Again",
  "email": "laith@gmail.com",
  "password": "123",
  "password_again": "123",
  "roles": "can_nothing"
}

###
