"""empty message

Revision ID: 67ebb2e46b76
Revises: 4f971a42572f
Create Date: 2018-05-01 02:55:24.615495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ebb2e46b76'
down_revision = '4f971a42572f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('password_again', sa.String(length=128), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_model_email'), 'base_model', ['email'], unique=True)
    op.create_index(op.f('ix_base_model_username'), 'base_model', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_model_username'), table_name='base_model')
    op.drop_index(op.f('ix_base_model_email'), table_name='base_model')
    op.drop_table('base_model')
    # ### end Alembic commands ###
